baseurl: "https://lockdown.ubnetdef.org/"
languageCode: "en-us"
title: "Lockdown"
theme: "vec"
disableHugoGeneratorInject: true

menu:
  main:
    - Name: "about"
      Weight: -100
      URL: "/about"
    - Name: "registration"
      Weight: -90
      URL: "/registration"
    - Name: "rules"
      Weight: -80
      URL: "/rules"
